Battleship/config/routes.rb
Rails.application.routes.draw do

  root "games#index"


  put "/boards/:board_id/shots", to: "games#shots"
  get "/games/:game_id/update_game", to: "games#update_game"
  resources :games
  resources :users, only: [:new, :create, :show, :destroy]
  resources :sessions, only: [:new, :create, :destroy]

  resources :boards do
    resources :ships
  end

end

Battleship/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Battleship/app/models/board.rb
class Board < ApplicationRecord
  belongs_to :player, class_name: "User"
  belongs_to :game
  has_many :ships
end

Battleship/app/models/game.rb
class Game < ApplicationRecord
  belongs_to :player1, class_name: "User"
  belongs_to :player2, class_name: "User"
  has_many :boards
end

Battleship/app/models/ship.rb
class Ship < ApplicationRecord
  belongs_to :board
end

Battleship/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :hosted_games, class_name: "Game", foreign_key: :player1_id
  has_many :joined_games, class_name: "Game", foreign_key: :player2_id
  has_many :boards, foreign_key: :player_id
  has_many :ships, through: :boards

  def games_played
    self.hosted_games.length + self.joined_games.length
  end

  def games_lost
    self.games_played - self.wins
  end
end

Battleship/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Battleship/app/controllers/games_controller.rb
class GamesController < ApplicationController
  include SessionsHelper

  def index
    @game = Game.new
  end

  def show
    @game = Game.find_by(id: params[:id])
    @board = @game.boards.find_by(player_id: current_user.id)
  end

  def create

  end

  def new
    @game = Game.new({player1_id:  current_user.id,
                     player2_id: current_user.id})

    if @game.save
      @board = Board.new({player_id:  current_user.id,
                          game_id: @game.id})
      @board.save

    else
      flash[:alert] = @game.errors.full_messages
      render 'new'
    end
  end

  def shots
    @board = Board.find_by(id: params[:board_id].to_i)
    if shots_helper(params)
      render :json => { :file_content => "true"}
    else
      render :json => { :file_content => "false"}
    end
  end

  def update_game
    @game = Game.find(params[:game_id])
    @board = Board.find_by(player_id: current_user.id, game_id: params[:game_id])
    # @opponent_board = @game.boards.reject {|board| board.id == @board.id}
    # response = {}
    # response[:shots] = parse_hits(@opponent_board)
    # if response[:shots].count("hit") >= 17
    #   response[:win_state] = "You win!"
    # end
    response[:ships] = @board.ships.each {|ship| ship.position + " "}
    response[:opponent_shots] = parse_hits(@board)
    if response[:opponent_shots].count("hit") >= 17
      response[:win_state] = "You lost! Aaargh."
     end
    render :json => response
  end

  def destroy
  end
end

Battleship/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    p "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
    p sessions_params
    user = User.find_by(email: sessions_params[:email])
    if user.authenticate(sessions_params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash.alert = "Invalid login info"
      render 'new'
    end
  end



  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private
  def sessions_params
    params.require(:session).permit(:email, :password)
  end
end

Battleship/app/controllers/ships_controller.rb
class ShipsController < ApplicationController
  layout false
  include ShipsHelper

  def index
    @player1_board = Board.find_by(player_id: current_user)
  end

  def create
    position = find_position(params[:position], params[:size], params[:direction])
    p position
    position = position.join(' ')
    ship_hash = {type_name: params[:name], position: position, size: params[:size], board_id: params[:board_id]}
    @ship = Ship.new(ship_hash)
    @ship.save
    return "Please"
  end

end

Battleship/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.new(users_params)
    if user.save
      session[:user_id] = user.id
      redirect_to root_path
    else
      @errors = user.errors.full_messages
      render 'new'
    end
  end

  def destroy
    user = User.find_by(id: params[:id])
    user.destroy
  end

  def show
    @user = User.find_by(id: params[:id])
    @games = @user.hosted_games + @user.joined_games
  end

  private
  def users_params
    params.require(:user).permit(:username, :email, :password)
  end
end

Battleship/app/helpers/application_helper.rb
module ApplicationHelper
end

Battleship/app/helpers/games_helper.rb
module GamesHelper

  def grid_converter(position)
    coords = {

    }
  end
end

  def shots_helper(params)
    @board = Board.find_by(id: params[:board_id].to_i)
    p "~~~~~~~"
    p params
    p params[:shot]
    p @board.shots
    p params[:board_id]
    @board.shots += " " + params[:shot]
    @board.save
    ship_array = @board.ships
    shot = params[:shot]
    ship_array.each do |ship|
      shot_array = @board.shots.split(' ')
      shot_array.each do |ship_shot|
        if ship_shot == shot
           true
        end
      end
    end
     false
  end


  def parse_hits(board)
    ship_array = board.ships
    shot_array = board.shots.split(" ")
    output_string = ""
    ship_array.each do |ship|
      ship_location = ship.position.split(" ")
      ship_location.each do |square|
        shot_array.each do |shot|
          output_string += shot + " "
          if shot == square
            output_string += "hit" + " "
          else
            output_string += "miss" + " "
          end
        end
      end
      output_string
    end
  end

Battleship/app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) # if @current_user comes back nil, find the user in the database with the id that matches the 'user_id' in the 'session' hash and assign it to @current_user
  end

  def logged_in?
    !!current_user
  end

  def set_session(user)
    session[:user_id] = user.id
  end

end

Battleship/app/helpers/ships_helper.rb
module ShipsHelper

  ALPHABET = ['A','B','C','D','E','F','G','H','I','J']

  def find_position(position, size, direction)
    if direction == "horizontal"
      find_position_horizontal(position,size)
    else
      find_position_vertical(position, size)
    end
  end

  def find_position_horizontal(position, size)
    p "~~~~~~~~~~~~~~~~~~~~~~~"
    p "I did a thing"
    position_letter = position.split('')[0]
    position_num = position.split('')[1]
    matched_letter_index = ALPHABET.index(position_letter)
    letters_array = Array.new
    new_array = ALPHABET.slice(0..matched_letter_index)
    new_array.reverse!.each do |char|
      if (letters_array.length.to_i) == size.to_i
        break
      else
        letters_array << char + position_num
      end
    end
    letters_array
  end

  def find_position_vertical(position, size)
    size = size.to_i
    position_letter= position.split('')[0]
    position_num = position.split("")[1].to_i
    output_array = []
    output_array << position
    temp_string = ""
    runner = true
    size -= 1
    while runner
      if size == 0
        runner = false
      else
        position_num -= 1
        temp_string = position_letter + position_num.to_s
        output_array << temp_string
        size -= 1
      end
    end
    output_array
  end
end

Battleship/app/helpers/users_helper.rb
module UsersHelper
  def current_user
    @user ||= User.find_by(id: session[:user_id])
  end

  def user_rankings
    @users = User.all
    @users.sort {|a,b| b.wins <=> a.wins}
  end

  def user_ranking(user_object)
    users = user_rankings
    users.index(user_object) + 1
  end

  def total_users
    User.all.length
  end
end

Battleship/app/views/games/destroy.html.erb
<h1>Games#destroy</h1>
<p>Find me in app/views/games/destroy.html.erb</p>

Battleship/app/views/games/index.html.erb
<%= link_to "Go to war!", new_game_path %>

Battleship/app/views/games/new.html.erb
<div class="set-up" id="grid">
<table style="text-align: center;">
  <tr>
    <th></th>
    <th>A</th>
    <th>B</th>
    <th>C</th>
    <th>D</th>
    <th>E</th>
    <th>F</th>
    <th>G</th>
    <th>H</th>
    <th>I</th>
    <th>J</th>
  </tr>
  <tr>
    <th>1</th>
    <td class="cell">A1</a></td>
    <td class="cell">B1</a></td>
    <td class="cell">C1</a></td>
    <td class="cell">D1</a></td>
    <td class="cell">E1</a></td>
    <td class="cell">F1</a></td>
    <td class="cell">G1</a></td>
    <td class="cell">H1</a></td>
    <td class="cell">I1</a></td>
    <td class="cell">J1</a></td>
  </tr>
  <tr>
    <th>2</th>
    <td class="cell">A2</a></td>
    <td class="cell">B2</a></td>
    <td class="cell">C2</a></td>
    <td class="cell">D2</a></td>
    <td class="cell">E2</a></td>
    <td class="cell">F2</a></td>
    <td class="cell">G2</a></td>
    <td class="cell">H2</a></td>
    <td class="cell">I2</a></td>
    <td class="cell">J2</a></td>
  </tr>
  <tr>
    <th>3</th>
    <td class="cell">A3</a></td>
    <td class="cell">B3</a></td>
    <td class="cell">C3</a></td>
    <td class="cell">D3</a></td>
    <td class="cell">E3</a></td>
    <td class="cell">F3</a></td>
    <td class="cell">G3</a></td>
    <td class="cell">H3</a></td>
    <td class="cell">I3</a></td>
    <td class="cell">J3</a></td>
  </tr>
  <tr>
    <th>4</th>
    <td class="cell">A4</a></td>
    <td class="cell">B4</a></td>
    <td class="cell">C4</a></td>
    <td class="cell">D4</a></td>
    <td class="cell">E4</a></td>
    <td class="cell">F4</a></td>
    <td class="cell">G4</a></td>
    <td class="cell">H4</a></td>
    <td class="cell">I4</a></td>
    <td class="cell">J4</a></td>
  </tr>
  <tr>
    <th>5</th>
    <td class="cell">A5</a></td>
    <td class="cell">B5</a></td>
    <td class="cell">C5</a></td>
    <td class="cell">D5</a></td>
    <td class="cell">E5</a></td>
    <td class="cell">F5</a></td>
    <td class="cell">G5</a></td>
    <td class="cell">H5</a></td>
    <td class="cell">I5</a></td>
    <td class="cell">J5</a></td>
  </tr>
  <tr>
    <th>6</th>
    <td class="cell">A6</a></td>
    <td class="cell">B6</a></td>
    <td class="cell">C6</a></td>
    <td class="cell">D6</a></td>
    <td class="cell">E6</a></td>
    <td class="cell">F6</a></td>
    <td class="cell">G6</a></td>
    <td class="cell">H6</a></td>
    <td class="cell">I6</a></td>
    <td class="cell">J6</a></td>
  </tr>
  <tr>
    <th>7</th>
    <td class="cell">A7</a></td>
    <td class="cell">B7</a></td>
    <td class="cell">C7</a></td>
    <td class="cell">D7</a></td>
    <td class="cell">E7</a></td>
    <td class="cell">F7</a></td>
    <td class="cell">G7</a></td>
    <td class="cell">H7</a></td>
    <td class="cell">I7</a></td>
    <td class="cell">J7</a></td>
  </tr>
  <tr>
    <th>8</th>
    <td class="cell">A8</a></td>
    <td class="cell">B8</a></td>
    <td class="cell">C8</a></td>
    <td class="cell">D8</a></td>
    <td class="cell">E8</a></td>
    <td class="cell">F8</a></td>
    <td class="cell">G8</a></td>
    <td class="cell">H8</a></td>
    <td class="cell">I8</a></td>
    <td class="cell">J8</a></td>
  </tr>
  <tr>
    <th>9</th>
    <td class="cell">A9</a></td>
    <td class="cell">B9</a></td>
    <td class="cell">C9</a></td>
    <td class="cell">D9</a></td>
    <td class="cell">E9</a></td>
    <td class="cell">F9</a></td>
    <td class="cell">G9</a></td>
    <td class="cell">H9</a></td>
    <td class="cell">I9</a></td>
    <td class="cell">J9</a></td>
  </tr>
  <tr>
    <th>10</th>
    <td class="cell">A10</a></td>
    <td class="cell">B10</a></td>
    <td class="cell">C10</a></td>
    <td class="cell">D10</a></td>
    <td class="cell">E10</a></td>
    <td class="cell">F10</a></td>
    <td class="cell">G10</a></td>
    <td class="cell">H10</a></td>
    <td class="cell">I10</a></td>
    <td class="cell">J10</a></td>
  </tr>
</table>
</div>


<%= link_to "Create Battle", @game %>



<h1 id="warning"></h1>
<h1><%=flash.alert%></h1>

Battleship/app/views/games/show.html.erb
<h1>Shot Board</h1>
<div id="shot-board">
<table style="text-align: center;">
  <tr>
    <th></th>
    <th>A</th>
    <th>B</th>
    <th>C</th>
    <th>D</th>
    <th>E</th>
    <th>F</th>
    <th>G</th>
    <th>H</th>
    <th>I</th>
    <th>J</th>
  </tr>
  <tr>
    <th>1</th>
    <td class="scell">A1</td>
    <td class="scell">B1</td>
    <td class="scell">C1</td>
    <td class="scell">D1</td>
    <td class="scell">E1</td>
    <td class="scell">F1</td>
    <td class="scell">G1</td>
    <td class="scell">H1</td>
    <td class="scell">I1</td>
    <td class="scell">J1</td>
  </tr>
  <tr>
    <th>2</th>
    <td class="scell">A2</td>
    <td class="scell">B2</td>
    <td class="scell">C2</td>
    <td class="scell">D2</td>
    <td class="scell">E2</td>
    <td class="scell">F2</td>
    <td class="scell">G2</td>
    <td class="scell">H2</td>
    <td class="scell">I2</td>
    <td class="scell">J2</td>
  </tr>
  <tr>
    <th>3</th>
    <td class="scell">A3</td>
    <td class="scell">B3</td>
    <td class="scell">C3</td>
    <td class="scell">D3</td>
    <td class="scell">E3</td>
    <td class="scell">F3</td>
    <td class="scell">G3</td>
    <td class="scell">H3</td>
    <td class="scell">I3</td>
    <td class="scell">J3</td>
  </tr>
  <tr>
    <th>4</th>
    <td class="scell">A4</td>
    <td class="scell">B4</td>
    <td class="scell">C4</td>
    <td class="scell">D4</td>
    <td class="scell">E4</td>
    <td class="scell">F4</td>
    <td class="scell">G4</td>
    <td class="scell">H4</td>
    <td class="scell">I4</td>
    <td class="scell">J4</td>
  </tr>
  <tr>
    <th>5</th>
    <td class="scell">A5</td>
    <td class="scell">B5</td>
    <td class="scell">C5</td>
    <td class="scell">D5</td>
    <td class="scell">E5</td>
    <td class="scell">F5</td>
    <td class="scell">G5</td>
    <td class="scell">H5</td>
    <td class="scell">I5</td>
    <td class="scell">J5</td>
  </tr>
  <tr>
    <th>6</th>
    <td class="scell">A6</td>
    <td class="scell">B6</td>
    <td class="scell">C6</td>
    <td class="scell">D6</td>
    <td class="scell">E6</td>
    <td class="scell">F6</td>
    <td class="scell">G6</td>
    <td class="scell">H6</td>
    <td class="scell">I6</td>
    <td class="scell">J6</td>
  </tr>
  <tr>
    <th>7</th>
    <td class="scell">A7</td>
    <td class="scell">B7</td>
    <td class="scell">C7</td>
    <td class="scell">D7</td>
    <td class="scell">E7</td>
    <td class="scell">F7</td>
    <td class="scell">G7</td>
    <td class="scell">H7</td>
    <td class="scell">I7</td>
    <td class="scell">J7</td>
  </tr>
  <tr>
    <th>8</th>
    <td class="scell">A8</td>
    <td class="scell">B8</td>
    <td class="scell">C8</td>
    <td class="scell">D8</td>
    <td class="scell">E8</td>
    <td class="scell">F8</td>
    <td class="scell">G8</td>
    <td class="scell">H8</td>
    <td class="scell">I8</td>
    <td class="scell">J8</td>
  </tr>
  <tr>
    <th>9</th>
    <td class="scell">A9</td>
    <td class="scell">B9</td>
    <td class="scell">C9</td>
    <td class="scell">D9</td>
    <td class="scell">E9</td>
    <td class="scell">F9</td>
    <td class="scell">G9</td>
    <td class="scell">H9</td>
    <td class="scell">I9</td>
    <td class="scell">J9</td>
  </tr>
  <tr>
    <th>10</th>
    <td class="scell">A10</td>
    <td class="scell">B10</td>
    <td class="scell">C10</td>
    <td class="scell">D10</td>
    <td class="scell">E10</td>
    <td class="scell">F10</td>
    <td class="scell">G10</td>
    <td class="scell">H10</td>
    <td class="scell">I10</td>
    <td class="scell">J10</td>
  </tr>
</table>
</div>



<h1>Your Board</h1>
<div id="grid">
<table style="text-align: center;">
  <tr>
    <th></th>
    <th>A</th>
    <th>B</th>
    <th>C</th>
    <th>D</th>
    <th>E</th>
    <th>F</th>
    <th>G</th>
    <th>H</th>
    <th>I</th>
    <th>J</th>
  </tr>
  <tr>
    <th>1</th>
    <td class="cell">A1</a></td>
    <td class="cell">B1</a></td>
    <td class="cell">C1</a></td>
    <td class="cell">D1</a></td>
    <td class="cell">E1</a></td>
    <td class="cell">F1</a></td>
    <td class="cell">G1</a></td>
    <td class="cell">H1</a></td>
    <td class="cell">I1</a></td>
    <td class="cell">J1</a></td>
  </tr>
  <tr>
    <th>2</th>
    <td class="cell">A2</a></td>
    <td class="cell">B2</a></td>
    <td class="cell">C2</a></td>
    <td class="cell">D2</a></td>
    <td class="cell">E2</a></td>
    <td class="cell">F2</a></td>
    <td class="cell">G2</a></td>
    <td class="cell">H2</a></td>
    <td class="cell">I2</a></td>
    <td class="cell">J2</a></td>
  </tr>
  <tr>
    <th>3</th>
    <td class="cell">A3</a></td>
    <td class="cell">B3</a></td>
    <td class="cell">C3</a></td>
    <td class="cell">D3</a></td>
    <td class="cell">E3</a></td>
    <td class="cell">F3</a></td>
    <td class="cell">G3</a></td>
    <td class="cell">H3</a></td>
    <td class="cell">I3</a></td>
    <td class="cell">J3</a></td>
  </tr>
  <tr>
    <th>4</th>
    <td class="cell">A4</a></td>
    <td class="cell">B4</a></td>
    <td class="cell">C4</a></td>
    <td class="cell">D4</a></td>
    <td class="cell">E4</a></td>
    <td class="cell">F4</a></td>
    <td class="cell">G4</a></td>
    <td class="cell">H4</a></td>
    <td class="cell">I4</a></td>
    <td class="cell">J4</a></td>
  </tr>
  <tr>
    <th>5</th>
    <td class="cell">A5</a></td>
    <td class="cell">B5</a></td>
    <td class="cell">C5</a></td>
    <td class="cell">D5</a></td>
    <td class="cell">E5</a></td>
    <td class="cell">F5</a></td>
    <td class="cell">G5</a></td>
    <td class="cell">H5</a></td>
    <td class="cell">I5</a></td>
    <td class="cell">J5</a></td>
  </tr>
  <tr>
    <th>6</th>
    <td class="cell">A6</a></td>
    <td class="cell">B6</a></td>
    <td class="cell">C6</a></td>
    <td class="cell">D6</a></td>
    <td class="cell">E6</a></td>
    <td class="cell">F6</a></td>
    <td class="cell">G6</a></td>
    <td class="cell">H6</a></td>
    <td class="cell">I6</a></td>
    <td class="cell">J6</a></td>
  </tr>
  <tr>
    <th>7</th>
    <td class="cell">A7</a></td>
    <td class="cell">B7</a></td>
    <td class="cell">C7</a></td>
    <td class="cell">D7</a></td>
    <td class="cell">E7</a></td>
    <td class="cell">F7</a></td>
    <td class="cell">G7</a></td>
    <td class="cell">H7</a></td>
    <td class="cell">I7</a></td>
    <td class="cell">J7</a></td>
  </tr>
  <tr>
    <th>8</th>
    <td class="cell">A8</a></td>
    <td class="cell">B8</a></td>
    <td class="cell">C8</a></td>
    <td class="cell">D8</a></td>
    <td class="cell">E8</a></td>
    <td class="cell">F8</a></td>
    <td class="cell">G8</a></td>
    <td class="cell">H8</a></td>
    <td class="cell">I8</a></td>
    <td class="cell">J8</a></td>
  </tr>
  <tr>
    <th>9</th>
    <td class="cell">A9</a></td>
    <td class="cell">B9</a></td>
    <td class="cell">C9</a></td>
    <td class="cell">D9</a></td>
    <td class="cell">E9</a></td>
    <td class="cell">F9</a></td>
    <td class="cell">G9</a></td>
    <td class="cell">H9</a></td>
    <td class="cell">I9</a></td>
    <td class="cell">J9</a></td>
  </tr>
  <tr>
    <th>10</th>
    <td class="cell">A10</a></td>
    <td class="cell">B10</a></td>
    <td class="cell">C10</a></td>
    <td class="cell">D10</a></td>
    <td class="cell">E10</a></td>
    <td class="cell">F10</a></td>
    <td class="cell">G10</a></td>
    <td class="cell">H10</a></td>
    <td class="cell">I10</a></td>
    <td class="cell">J10</a></td>
  </tr>
</table>
</div>


<div id="ships">
<p class="ship" value="2">Destroyer</p><br><br>
<p class="ship" value="3">Submarine</p><br><br>
<p class="ship" value="3">Cruiser</p><br><br>
<p class="ship" value="4">BattleShip</p><br><br>
<p class="ship" value="5">Carrier</p><br><br><br>
</div>


<div id="ready-button"> <h1>Ready</h1></div>
<div id="toggle-button">
    <button>Rotate Ship</button>
</div>
<h2 id="board-id" class="hidden"><%=@board.id%></h2>
<div id="game-id" style="display: none"><%= @game.id %></div>

Battleship/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Battleship</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <nav>
    <%= link_to "Home", games_path %>
    <% if logged_in? %>
      <%= link_to "#{current_user.username.capitalize}", current_user %>
      <%= link_to "Logout", "/sessions/#{session[:user_id]}", method: :delete %>
    <% else %>
      <%= link_to "Register", new_user_path %>
      <%= link_to "Login", new_session_path %>
    <% end %>
  </nav>
  <body>
    <%= yield %>
  </body>
</html>

Battleship/app/views/ships/index.html.erb
<h1>Ships#index</h1>
<p>Find me in app/views/ships/index.html.erb</p>

Battleship/app/views/users/new.html.erb
<h1> Arrrr matey, create yr account </h1>

<%= form_for :user, url: @user do |f| %>
  <%= f.label :usarrrrrname %>
  <%= f.text_field :username %><br>
  <%= f.label :email %>
  <%= f.text_field :email %><br>
  <%= f.label :password %>
  <%= f.text_field :password %><br>
  <%= f.submit %>
<% end %>

Battleship/app/views/users/show.html.erb
<h1> Welcome <%= @user.username.capitalize %></h1>
<ul>
<li> You're currently rank <%= user_ranking(@user) %> out of <%= total_users %> </li>
<li> You've played <%= @user.games_played %> games </li>
<li> You've hosted <%= @user.hosted_games.length %> games </li>
<li> You've joined <%= @user.joined_games.length %> games </li>
<li> You've won <%= @user.wins %> games </li>
<li> You've lost <%= @user.games_lost %> games, Scallywag!</li>
</ul>

<ol>
  <%@games.each do |game|%>
  <li><a href="/games/<%=game.id%>"><%=game.player1.username%> vs. <%=game.player2.username%></a></li>
  <% end%>
</ol>